
name: BanSystem
main: bansystem\BanSystem
version: 2.0
author: xXSuperFrostyXx, randy128gamer
api: [4.0.0]
description: A ban system that allows to temporarily/permanently ban/mute/block and kick players/IP address.
